language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-blueman' ]; then cd .. && eval "mv $currentfolder generator-blueman" && cd generator-blueman; fi

